/* XPM */
static xpm_row_t forca3[]= {
/* columns rows colors chars-per-pixel */
"187 168 2 1 ",
"  c #000000",
"X c #FFFFFF",
/* pixels */
"                                                                                                                                                                                           ",
"                                                                                                                                                                                           ",
"                                                                                                                                                                                           ",
"                                                                                                                                                                                           ",
"                                                                                                                                                                                           ",
"                                            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                 ",
"                                          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                ",
"                                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                               ",
"                                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                              ",
"                                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                              ",
"                                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                               ",
"                                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                               ",
"                                         XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX                                                                ",
"                                         XXXXXXXX                 XXXXXXXXXXXX                                        XXXX                                                                 ",
"                                         XXXXXXXX                XXXXXXXXXXXX                                         XXXX                                                                 ",
"                                         XXXXXXXX               XXXXXXXXXXXX                                          XXXX                                                                 ",
"                                         XXXXXXXX              XXXXXXXXXXXX                                           XXXX                                                                 ",
"                                         XXXXXXXX             XXXXXXXXXXXX                                            XXXX                                                                 ",
"                                         XXXXXXXX            XXXXXXXXXXXX                                             XXXX                                                                 ",
"                                         XXXXXXXX           XXXXXXXXXXXX                                              XXXX                                                                 ",
"                                         XXXXXXXX          XXXXXXXXXXXX                                               XXXX                                                                 ",
"                                         XXXXXXXX         XXXXXXXXXXXX                                                XXXX                                                                 ",
"                                         XXXXXXXX        XXXXXXXXXXXX                                                 XXXX                                                                 ",
"                                         XXXXXXXX       XXXXXXXXXXXX                                                  XXXX                                                                 ",
"                                         XXXXXXXX      XXXXXXXXXXXX                                                   XXXX                                                                 ",
"                                         XXXXXXXX     XXXXXXXXXXXX                                                    XXXX                                                                 ",
"                                         XXXXXXXX    XXXXXXXXXXXX                                                     XXXX                                                                 ",
"                                         XXXXXXXX   XXXXXXXXXXXX                                                      XXXX                                                                 ",
"                                         XXXXXXXX  XXXXXXXXXXXX                                                       XXXX                                                                 ",
"                                         XXXXXXXX XXXXXXXXXXXX                                                        XXXX                                                                 ",
"                                         XXXXXXXXXXXXXXXXXXXX                                                         XXXX                                                                 ",
"                                         XXXXXXXXXXXXXXXXXXX                                                          XXXX                                                                 ",
"                                         XXXXXXXXXXXXXXXXXX                                                           XXXX                                                                 ",
"                                         XXXXXXXXXXXXXXXXX                                                            XXXX                                                                 ",
"                                         XXXXXXXXXXXXXXXX                                                             XXXX                                                                 ",
"                                         XXXXXXXXXXXXXXX                                                              XXXX                                                                 ",
"                                         XXXXXXXXXXXXXX                                                               XXXX                                                                 ",
"                                         XXXXXXXXXXXXX                                                                XXXX                                                                 ",
"                                         XXXXXXXXXXXX                                                                 XXXX                                                                 ",
"                                         XXXXXXXXXXX                                                                  XXXX                                                                 ",
"                                         XXXXXXXXXX                                                                   XXXX                                                                 ",
"                                         XXXXXXXXX                                                                    XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                   XXXXXXXXX                                                              ",
"                                         XXXXXXXX                                                                 XXXXXXXXXXXXX                                                            ",
"                                         XXXXXXXX                                                               XXXXXXXXXXXXXXXXX                                                          ",
"                                         XXXXXXXX                                                              XXXXXXXXXXXXXXXXXXX                                                         ",
"                                         XXXXXXXX                                                             XXXXXXX       XXXXXXX                                                        ",
"                                         XXXXXXXX                                                            XXXXXX           XXXXXX                                                       ",
"                                         XXXXXXXX                                                           XXXXXX             XXXXX                                                       ",
"                                         XXXXXXXX                                                           XXXXX               XXXXX                                                      ",
"                                         XXXXXXXX                                                          XXXXX                 XXXX                                                      ",
"                                         XXXXXXXX                                                          XXXXX                 XXXXX                                                     ",
"                                         XXXXXXXX                                                          XXXX                   XXXX                                                     ",
"                                         XXXXXXXX                                                          XXXX                   XXXX                                                     ",
"                                         XXXXXXXX                                                          XXXX                   XXXX                                                     ",
"                                         XXXXXXXX                                                          XXXX                   XXXX                                                     ",
"                                         XXXXXXXX                                                          XXXX                   XXXX                                                     ",
"                                         XXXXXXXX                                                          XXXX                   XXXX                                                     ",
"                                         XXXXXXXX                                                          XXXX                   XXXX                                                     ",
"                                         XXXXXXXX                                                          XXXXX                 XXXXX                                                     ",
"                                         XXXXXXXX                                                           XXXX                 XXXX                                                      ",
"                                         XXXXXXXX                                                           XXXXX               XXXXX                                                      ",
"                                         XXXXXXXX                                                            XXXXX             XXXXXX                                                      ",
"                                         XXXXXXXX                                                            XXXXXX           XXXXXX                                                       ",
"                                         XXXXXXXX                                                             XXXXXXX       XXXXXXX                                                        ",
"                                         XXXXXXXX                                                              XXXXXXXXXXXXXXXXXXX                                                         ",
"                                         XXXXXXXX                                                               XXXXXXXXXXXXXXXXX                                                          ",
"                                         XXXXXXXX                                                                 XXXXXXXXXXXXXX                                                           ",
"                                         XXXXXXXX                                                                  XXXXXXXXXXX                                                             ",
"                                         XXXXXXXX                                                                  XXXXXXX                                                                 ",
"                                         XXXXXXXX                                                                 XXXXXXXX                                                                 ",
"                                         XXXXXXXX                                                                XXXXXXXXX                                                                 ",
"                                         XXXXXXXX                                                               XXXXXXXXXX                                                                 ",
"                                         XXXXXXXX                                                              XXXXXX XXXX                                                                 ",
"                                         XXXXXXXX                                                             XXXXXX  XXXX                                                                 ",
"                                         XXXXXXXX                                                            XXXXXX   XXXX                                                                 ",
"                                         XXXXXXXX                                                           XXXXXX    XXXX                                                                 ",
"                                         XXXXXXXX                                                          XXXXXX     XXXX                                                                 ",
"                                         XXXXXXXX                                                         XXXXXX      XXXX                                                                 ",
"                                         XXXXXXXX                                                        XXXXXX       XXXX                                                                 ",
"                                         XXXXXXXX                                                       XXXXXX        XXXX                                                                 ",
"                                         XXXXXXXX                                                      XXXXXX         XXXX                                                                 ",
"                                         XXXXXXXX                                                     XXXXXX          XXXX                                                                 ",
"                                         XXXXXXXX                                                    XXXXXX           XXXX                                                                 ",
"                                         XXXXXXXX                                                   XXXXXX            XXXX                                                                 ",
"                                         XXXXXXXX                                                  XXXXXX             XXXX                                                                 ",
"                                         XXXXXXXX                                                 XXXXXX              XXXX                                                                 ",
"                                         XXXXXXXX                                                 XXXXX               XXXX                                                                 ",
"                                         XXXXXXXX                                                  XXX                XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                     XXXX                                                                 ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"                                         XXXXXXXX                                                                                                                                          ",
"        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        ",
"       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       ",
"      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       ",
"      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       ",
"      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       ",
"      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX       ",
"       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX        ",
"        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX         ",
"                                                                                                                                                                                           ",
"                                                                                                                                                                                           "
};
