/* XPM */
static xpm_row_t forca6[] = {
/* columns rows colors chars-per-pixel */
"187 168 2 1",
"  c #000000",
"o c #FFFFFF",
/* pixels */
"                                                                                                                                                                                           ",
"                                                                                                                                                                                           ",
"                                                                                                                                                                                           ",
"                                                                                                                                                                                           ",
"                                                                                                                                                                                           ",
"                                            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                                 ",
"                                          ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                                ",
"                                          oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                               ",
"                                         oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                              ",
"                                         oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                              ",
"                                         ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                               ",
"                                         ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                               ",
"                                         oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                                ",
"                                         oooooooo                 oooooooooooo                                        oooo                                                                 ",
"                                         oooooooo                oooooooooooo                                         oooo                                                                 ",
"                                         oooooooo               oooooooooooo                                          oooo                                                                 ",
"                                         oooooooo              oooooooooooo                                           oooo                                                                 ",
"                                         oooooooo             oooooooooooo                                            oooo                                                                 ",
"                                         oooooooo            oooooooooooo                                             oooo                                                                 ",
"                                         oooooooo           oooooooooooo                                              oooo                                                                 ",
"                                         oooooooo          oooooooooooo                                               oooo                                                                 ",
"                                         oooooooo         oooooooooooo                                                oooo                                                                 ",
"                                         oooooooo        oooooooooooo                                                 oooo                                                                 ",
"                                         oooooooo       oooooooooooo                                                  oooo                                                                 ",
"                                         oooooooo      oooooooooooo                                                   oooo                                                                 ",
"                                         oooooooo     oooooooooooo                                                    oooo                                                                 ",
"                                         oooooooo    oooooooooooo                                                     oooo                                                                 ",
"                                         oooooooo   oooooooooooo                                                      oooo                                                                 ",
"                                         oooooooo  oooooooooooo                                                       oooo                                                                 ",
"                                         oooooooo oooooooooooo                                                        oooo                                                                 ",
"                                         oooooooooooooooooooo                                                         oooo                                                                 ",
"                                         ooooooooooooooooooo                                                          oooo                                                                 ",
"                                         oooooooooooooooooo                                                           oooo                                                                 ",
"                                         ooooooooooooooooo                                                            oooo                                                                 ",
"                                         oooooooooooooooo                                                             oooo                                                                 ",
"                                         ooooooooooooooo                                                              oooo                                                                 ",
"                                         oooooooooooooo                                                               oooo                                                                 ",
"                                         ooooooooooooo                                                                oooo                                                                 ",
"                                         oooooooooooo                                                                 oooo                                                                 ",
"                                         ooooooooooo                                                                  oooo                                                                 ",
"                                         oooooooooo                                                                   oooo                                                                 ",
"                                         ooooooooo                                                                    oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                   ooooooooo                                                              ",
"                                         oooooooo                                                                 ooooooooooooo                                                            ",
"                                         oooooooo                                                               ooooooooooooooooo                                                          ",
"                                         oooooooo                                                              ooooooooooooooooooo                                                         ",
"                                         oooooooo                                                             ooooooo       ooooooo                                                        ",
"                                         oooooooo                                                            oooooo           oooooo                                                       ",
"                                         oooooooo                                                            ooooo             ooooo                                                       ",
"                                         oooooooo                                                           ooooo               ooooo                                                      ",
"                                         oooooooo                                                           oooo                 oooo                                                      ",
"                                         oooooooo                                                          ooooo                 ooooo                                                     ",
"                                         oooooooo                                                          oooo                   oooo                                                     ",
"                                         oooooooo                                                          oooo                   oooo                                                     ",
"                                         oooooooo                                                          oooo                   oooo                                                     ",
"                                         oooooooo                                                          oooo                   oooo                                                     ",
"                                         oooooooo                                                          oooo                   oooo                                                     ",
"                                         oooooooo                                                          oooo                   oooo                                                     ",
"                                         oooooooo                                                          oooo                   oooo                                                     ",
"                                         oooooooo                                                          ooooo                 ooooo                                                     ",
"                                         oooooooo                                                           oooo                 oooo                                                      ",
"                                         oooooooo                                                           ooooo               ooooo                                                      ",
"                                         oooooooo                                                            ooooo             ooooo                                                       ",
"                                         oooooooo                                                            oooooo           oooooo                                                       ",
"                                         oooooooo                                                             ooooooo       ooooooo                                                        ",
"                                         oooooooo                                                              ooooooooooooooooooo                                                         ",
"                                         oooooooo                                                               ooooooooooooooooo                                                          ",
"                                         oooooooo                                                                 ooooooooooooo                                                            ",
"                                         oooooooo                                                                   oooooooooo                                                             ",
"                                         oooooooo                                                                  ooooooooooo                                                             ",
"                                         oooooooo                                                                 ooooooooooooo                                                            ",
"                                         oooooooo                                                                ooooooooooooooo                                                           ",
"                                         oooooooo                                                               oooooooooo oooooo                                                          ",
"                                         oooooooo                                                              oooooo oooo  oooooo                                                         ",
"                                         oooooooo                                                             oooooo  oooo   oooooo                                                        ",
"                                         oooooooo                                                            oooooo   oooo    oooooo                                                       ",
"                                         oooooooo                                                           oooooo    oooo     oooooo                                                      ",
"                                         oooooooo                                                          oooooo     oooo      oooooo                                                     ",
"                                         oooooooo                                                         oooooo      oooo       oooooo                                                    ",
"                                         oooooooo                                                        oooooo       oooo        oooooo                                                   ",
"                                         oooooooo                                                       oooooo        oooo         oooooo                                                  ",
"                                         oooooooo                                                      oooooo         oooo          oooooo                                                 ",
"                                         oooooooo                                                     oooooo          oooo           oooooo                                                ",
"                                         oooooooo                                                    oooooo           oooo            oooooo                                               ",
"                                         oooooooo                                                   oooooo            oooo             oooooo                                              ",
"                                         oooooooo                                                  oooooo             oooo              oooooo                                             ",
"                                         oooooooo                                                 oooooo              oooo               ooooo                                             ",
"                                         oooooooo                                                 ooooo               oooo                oooo                                             ",
"                                         oooooooo                                                  ooo                oooo                 ooo                                             ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     oooo                                                                 ",
"                                         oooooooo                                                                     ooooo                                                                ",
"                                         oooooooo                                                                    ooooooo                                                               ",
"                                         oooooooo                                                                   ooooooooo                                                              ",
"                                         oooooooo                                                                  ooooooooooo                                                             ",
"                                         oooooooo                                                                 oooooo oooooo                                                            ",
"                                         oooooooo                                                                oooooo   oooooo                                                           ",
"                                         oooooooo                                                               oooooo     oooooo                                                          ",
"                                         oooooooo                                                              oooooo       oooooo                                                         ",
"                                         oooooooo                                                             oooooo         oooooo                                                        ",
"                                         oooooooo                                                            oooooo           oooooo                                                       ",
"                                         oooooooo                                                           oooooo             oooooo                                                      ",
"                                         oooooooo                                                          oooooo               oooooo                                                     ",
"                                         oooooooo                                                         oooooo                 oooooo                                                    ",
"                                         oooooooo                                                        oooooo                   oooooo                                                   ",
"                                         oooooooo                                                       oooooo                     oooooo                                                  ",
"                                         oooooooo                                                      oooooo                       oooooo                                                 ",
"                                         oooooooo                                                     oooooo                         oooooo                                                ",
"                                         oooooooo                                                    oooooo                           oooooo                                               ",
"                                         oooooooo                                                   oooooo                             oooooo                                              ",
"                                         oooooooo                                                  oooooo                               oooooo                                             ",
"                                         oooooooo                                                 oooooo                                 ooooo                                             ",
"                                         oooooooo                                                 ooooo                                   oooo                                             ",
"                                         oooooooo                                                  ooo                                     ooo                                             ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"                                         oooooooo                                                                                                                                          ",
"        ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo        ",
"       ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo       ",
"      oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo       ",
"      oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo       ",
"      oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo       ",
"      oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo       ",
"       oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo        ",
"        oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo         ",
"                                                                                                                                                                                           ",
"                                                                                                                                                                                           "};
